# Generated by Django 3.2.4 on 2021-06-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=3)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='weatherapi.request')),
            ],
        ),
    ]
