# Generated by Django 3.2.4 on 2021-06-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='UserRequest',
        ),
    ]
