# Generated by Django 3.2.4 on 2021-06-23 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0002_rename_request_userrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='request',
            new_name='user_request',
        ),
    ]
