# Generated by Django 3.2.4 on 2021-06-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0004_auto_20210623_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
